### ISSUE TITLE
[epic] Remove "engine activate/check/update" subcommands

### ISSUE THREAD

**Issue by thaJeztah** [docker/cli#2213]
These subcommands were created to allow upgrading a Docker Community engine to Docker Enterprise, but never really took off. With the migration of the docker "enterprise" products to Mirantis, we should remove these subcommands as releases may no longer be done in sync in future.

- [x] https://github.com/docker/cli/pull/2207 Remove "docker engine" subcommands
- [x] https://github.com/docker/docker-ce-packaging/pull/411 Remove image-based build (for docker engine activate)
- [x] https://github.com/docker/docker-ce-packaging/pull/420 Remove some remnants related to image-based builds
- [x] https://github.com/docker/docker-ce-packaging/pull/426 Remove more remnants from image-based engine
- [x] https://github.com/docker/docker.github.io/pull/9984 Remove "docker engine" commands
- [x] updated deprecated features page (https://github.com/docker/cli/pull/2319)
- [x] changes in release-repositories
- [ ] backport (packaging changes only?) to 19.03 (and 18.09?) branches

**Comment by seemethere** [comment]
I believe https://github.com/docker/docker-ce-packaging/pull/411 should suffice

**Comment by thaJeztah** [comment]
Thanks for looking, @seemethere 🤗

**Comment by chris-crone** [comment]
@nebuk89 Do we still need to publish the EE images?

**Comment by thaJeztah** [comment]
Work for this is done for "master" / 20.03, we might still consider backporting to 19.03 packaging, but no need to track that here
