### ISSUE TITLE
[epic] remove experimental "docker (stack) deploy" using "dab" files

### ISSUE THREAD

**Issue by thaJeztah** [docker/cli#2215]
The top-level `docker deploy` command (using the "Docker Application Bundle" (`.dab`) file format was introduced as an experimental feature in Docker 1.13 / 17.03, but superseded by support for Docker Compose files (and `docker app` / CNAB).

With no development being done on this feature, and no active use of the file format, we will be removing support for the DAB file format, and the top-level `docker deploy` command (hidden by default in  19.03 through https://github.com/docker/cli/pull/1602), in favour of `docker stack deploy` using compose files.

- [x] remove top-level `docker deploy` command (https://github.com/docker/cli/pull/2216)
- [x] remove `--bundle-file` flags from commands (https://github.com/docker/cli/pull/2216)
- [x] remove the `docker-compose bundle` command (used to convert docker-compose files to `.dab`) (https://github.com/docker/compose/pull/7085)
- [x] update the documentation, and remove references to the `.dab` format and `docker deploy` subcommand (https://github.com/docker/docker.github.io/pull/9987).

**Comment by AkihiroSuda** [comment]
Any remaining issue?

**Comment by thaJeztah** [comment]
No, I think we're all set: we updated the documentation already (even though it's not "removed" yet from the current release, but doesn't hurt to limit exposure of the feature).

Let me close this one 👍
