### ISSUE TITLE
unit tests on commands

### ISSUE THREAD

**Issue by vdemeester** [docker/cli#37]
Moving initial `docker/docker` issue https://github.com/moby/moby/issues/31217 here  

This issue is to keep track of unit test for the cli (i.e. `cli/commands` package and sub-packages).

- [x] bundlefile
- [x] checkpoint @adshmh 
- [x] container (fakeClient added in #61) @vdemeester
- [x] formatter
- [x] idresolver @adshmh
- [x] image @icapurro moby/moby#32248 
- [x] inspect
- [x] network (fakeClient added in #132) @ksouf
- [x] node
- [x] plugin @adshmh 
- [x] prune
- [x] registry
- [x] secret @adshmh 
- [x] service
- [x] stack @adshmh 
- [x] swarm
- [x] system
- [x] task
- [x] trust
- [x] volume (https://github.com/moby/moby/pull/31124)

The `swarm`, `node` and `volume` packages are example on how to write those tests (but they probably can be enhance, and enhancement are always welcome ).

- In order to write tests for these, you'll have to create more builder (`cli/internal/test/builders`) for objects that are not yet there.
- You can also use `golden` files (see examples)
- For each of these package, there is some integration tests (in `integration-cli`) that could be removed. I tried to mark them when I saw them, but it's not complete yet. I'll try to update this issue with a list of integration test that could be gone for each packages.

**Comment by dnephin** [comment]
We may need to move some of the `fakeClient` into `cli/internal/test/` and export the struct and fields. There are some packages (stack, and service at least) that use parts of other clients.

**Comment by jeremcs** [comment]
Some items on the list seem to be deprecated as they do not appear when setting the DOCKER_HIDE_LEGACY_COMMANDS variable:
- bundlefile
- inspect
- prune
- registry
- task

Should we remove them from the list ?

(cc @kelu27)

**Comment by vdemeester** [comment]
@jeremcs I would say not (because some of them won't ever be removed).

**Comment by clook** [comment]
Starting working on service (https://github.com/docker/cli/issues/201)

**Comment by adshmh** [comment]
#dibs on checkpoint package.

**Comment by Zebrilee** [comment]
hi @vdemeester ,
I was working on prune test in the last hackergarten but I saw the commit two days ago which modify the [prune.go file and add a prune_test.go too](https://github.com/docker/cli/tree/master/cli/command/system). 
I believe this part is ok or is there something else to do?

**Comment by vdemeester** [comment]
@Zebrilee oh right yeah, I should mark it on the issue

**Comment by redpanda** [comment]
#dibs on network package.

**Comment by vdemeester** [comment]
Closing this as all those packages have some test. We can enhance the coverage but I feel this issue can be considered as done.
