### ISSUE TITLE
[k8s] prepare for next api extension version

### ISSUE THREAD

**Issue by vdemeester** [docker/cli#800]
The next version of the kube compose api extension will have significant changes, we need to prepare the upgrade (see below issues)

- [x] https://github.com/docker/cli/issues/799 new api version (`v1beta2`)
   - api-server instead of crd + controller
   - a struct is used by default instead of the composefile
- [ ] https://github.com/docker/cli/issues/797 support for `logs` server side (could implement a `docker stack logs` both for kubernetes and swarm)
- [ ] https://github.com/docker/cli/issues/798 support for `scale` server side (could implement a `docker stack scale service=20` both for kubernetes and swarm)
- [ ] Add e2e tests on both `v1beta1` and `v1beta2` version 👼

**Comment by olljanat** [comment]
@vdemeester I think that first step should be marked as done. Any time plan for other parts?

**Comment by adeniyistephen** [comment]
@vdemeester Hi, I would love to work on this, Please provide pointers and input on how to work on it. Thanks

**Comment by thaJeztah** [comment]
kubernetes integration was deprecated and removed; let me close this one
